[package]

name = "raisin"
version = "0.0.1"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.url]
git = "https://github.com/servo/rust-url.git"
