[package]

name = "rustless"
version = "0.5.8"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "Rustless is a REST-like API micro-framework for Rust."
keywords = ["api", "web", "hyper", "iron", "rest"]
readme = "README.md"
license = "MIT"

[lib]
name = "rustless"
path = "src/lib.rs"

[[test]]
name = "tests"

[features]
default = ["iron_backend"]
iron_backend = ["iron", "bodyparser", "plugin"]

[dependencies]
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
valico = "*"
queryst = "*"
jsonway = "*"
url = "*"
cookie = "*"
hyper = "*"
error = "*"
typemap = "*"
mopa = "*"
log = "*"

[dependencies.iron]
optional = true
version = "*"

[dependencies.bodyparser]
optional = true
version = "*"

[dependencies.plugin]
optional = true
version = "*"
